# Source YAML
# Reference documentation: https://docs.rilldata.com/reference/project-files/sources

type: source

connector: "duckdb"
sql: "select * from read_parquet('gs://metrics-in.rilldata.io/product-metrics/pg_snapshot/latest/service.parquet')"